/**
 * pdfService.js
 * Server-side PDF generation using pdfkit.
 * Produces two PDFs:
 *   A) Transcript PDF  — full timestamped transcript
 *   B) Summary PDF     — AI-generated summary, action items, decisions
 */

import PDFDocument from 'pdfkit';

// ─── Colours ──────────────────────────────────────────────────────────────────
const COLORS = {
  brand:       '#2563EB', // blue-600
  brandDark:   '#1E40AF', // blue-800
  accent:      '#059669', // emerald-600
  danger:      '#DC2626', // red-600
  purple:      '#7C3AED', // violet-600
  text:        '#111827', // gray-900
  muted:       '#6B7280', // gray-500
  light:       '#F9FAFB', // gray-50
  border:      '#E5E7EB', // gray-200
  white:       '#FFFFFF',
};

const FONT = {
  regular: 'Helvetica',
  bold:    'Helvetica-Bold',
  oblique: 'Helvetica-Oblique',
};

// ─── Shared utilities ─────────────────────────────────────────────────────────

function hexToRGB(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return [r, g, b];
}

function addPageNumbers(doc) {
  const range = doc.bufferedPageRange();
  const total = range.count;
  for (let i = 0; i < total; i++) {
    doc.switchToPage(range.start + i);
    doc
      .font(FONT.regular)
      .fontSize(8)
      .fillColor(COLORS.muted)
      .text(
        `Page ${i + 1} of ${total}  •  Generated by MeetCut`,
        50,
        doc.page.height - 30,
        { align: 'center', width: doc.page.width - 100 }
      );
  }
}

function drawHeader(doc, leftText, rightText) {
  doc.rect(0, 0, doc.page.width, 36).fill(COLORS.brand);
  doc.font(FONT.bold).fontSize(11).fillColor(COLORS.white);
  doc.text(leftText, 30, 12, { continued: true });
  doc.font(FONT.regular).fontSize(9).fillColor('#BFDBFE');
  doc.text(`   ${rightText}`, { align: 'right' });
}

function sectionTitle(doc, title, color = COLORS.brand) {
  const pageW = doc.page.width;
  const [r, g, b] = hexToRGB(color);
  if (doc.y > doc.page.height - 80) doc.addPage();
  doc.moveDown(0.5);
  doc.rect(40, doc.y, pageW - 80, 22).fill(color);
  doc.font(FONT.bold).fontSize(10.5).fillColor(COLORS.white);
  doc.text(title, 48, doc.y - 16);
  doc.moveDown(0.4);
  doc.fillColor(COLORS.text);
}

function bulletItem(doc, text, indent = 55) {
  const available = doc.page.width - indent - 50;
  if (doc.y > doc.page.height - 60) doc.addPage();
  const startY = doc.y;
  doc.font(FONT.regular).fontSize(10).fillColor(COLORS.brand);
  doc.text('•', indent - 10, startY);
  doc.font(FONT.regular).fontSize(10).fillColor(COLORS.text);
  doc.text(text, indent, startY, { width: available });
  doc.moveDown(0.2);
}

function infoRow(doc, label, value, y) {
  doc.font(FONT.bold).fontSize(9.5).fillColor(COLORS.muted).text(label, 50, y);
  doc.font(FONT.regular).fontSize(9.5).fillColor(COLORS.text).text(value, 160, y);
}

// ─── A) Transcript PDF ────────────────────────────────────────────────────────

/**
 * @param {object} opts
 * @param {string}   opts.meetingTitle
 * @param {string}   opts.dateTime
 * @param {string[]} opts.participants
 * @param {string}   opts.language
 * @param {number}   opts.durationSeconds
 * @param {Array}    opts.segments  — [{index, startFormatted, endFormatted, speaker, text}]
 * @param {string}   opts.fullText  — raw concatenated text (fallback if no segments)
 * @returns {Promise<Buffer>}
 */
export function generateTranscriptPDF(opts) {
  return new Promise((resolve, reject) => {
    const {
      meetingTitle = 'Meeting Transcript',
      dateTime = new Date().toLocaleString(),
      participants = [],
      language = 'en',
      durationSeconds = 0,
      segments = [],
      fullText = '',
    } = opts;

    const doc = new PDFDocument({ margin: 50, bufferPages: true, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ── Cover / first page header ──
    drawHeader(doc, 'MeetCut  —  Meeting Transcript', new Date().toLocaleDateString());
    doc.moveDown(2.2);

    // Title
    doc.font(FONT.bold).fontSize(20).fillColor(COLORS.text);
    doc.text(meetingTitle, 50, doc.y, { align: 'left' });
    doc.moveDown(0.3);
    doc.rect(50, doc.y, doc.page.width - 100, 2).fill(COLORS.brand);
    doc.moveDown(0.7);

    // Meta block
    const metaY = doc.y;
    infoRow(doc, 'Date / Time', dateTime, metaY);
    infoRow(doc, 'Language', language.toUpperCase(), metaY + 16);
    infoRow(doc, 'Duration', durationSeconds > 0 ? formatDuration(durationSeconds) : 'N/A', metaY + 32);
    infoRow(doc, 'Participants', participants.length ? participants.join(', ') : 'Not specified', metaY + 48);
    doc.y = metaY + 72;

    // ── Transcript body ──
    sectionTitle(doc, '  FULL TRANSCRIPT', COLORS.brandDark);

    if (segments.length > 0) {
      segments.forEach((seg) => {
        if (doc.y > doc.page.height - 80) doc.addPage();

        // Timestamp pill
        doc.font(FONT.bold).fontSize(8.5).fillColor(COLORS.white);
        const tsText = `${seg.startFormatted} → ${seg.endFormatted}`;
        const tsWidth = doc.widthOfString(tsText) + 14;
        doc.rect(50, doc.y, tsWidth, 14).fill(COLORS.brand);
        doc.text(tsText, 57, doc.y - 11);

        // Speaker
        if (seg.speaker) {
          doc.font(FONT.bold).fontSize(10).fillColor(COLORS.accent);
          doc.text(`${seg.speaker}:`, 50 + tsWidth + 8, doc.y - 12);
        }

        doc.moveDown(0.3);

        // Segment text
        doc.font(FONT.regular).fontSize(10.5).fillColor(COLORS.text);
        doc.text(seg.text, 55, doc.y, { width: doc.page.width - 110 });
        doc.moveDown(0.6);
        doc.rect(50, doc.y, doc.page.width - 100, 0.5).fill(COLORS.border);
        doc.moveDown(0.4);
      });
    } else {
      // Fallback: just dump full text
      doc.font(FONT.regular).fontSize(10.5).fillColor(COLORS.text);
      doc.text(fullText || 'No transcript content available.', 55, doc.y, {
        width: doc.page.width - 110,
      });
    }

    addPageNumbers(doc);
    doc.end();
  });
}

// ─── B) Summary PDF ───────────────────────────────────────────────────────────

/**
 * @param {object} summary — the Grok summary object
 * @returns {Promise<Buffer>}
 */
export function generateSummaryPDF(summary) {
  return new Promise((resolve, reject) => {
    const {
      meetingTitle = 'Meeting Summary',
      dateTime = new Date().toLocaleString(),
      participants = [],
      finalSummary = '',
      keyDiscussionPoints = [],
      decisionsTaken = [],
      actionItems = [],
      nextMeetingAgenda = [],
    } = summary;

    const doc = new PDFDocument({ margin: 50, bufferPages: true, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ── Header ──
    drawHeader(doc, 'MeetCut  —  Meeting Summary', new Date().toLocaleDateString());
    doc.moveDown(2.2);

    // Title
    doc.font(FONT.bold).fontSize(20).fillColor(COLORS.text);
    doc.text(meetingTitle, 50, doc.y);
    doc.moveDown(0.3);
    doc.rect(50, doc.y, doc.page.width - 100, 2).fill(COLORS.brand);
    doc.moveDown(0.7);

    // Meta
    const metaY = doc.y;
    infoRow(doc, 'Date / Time', dateTime, metaY);
    infoRow(doc, 'Participants', participants.length ? participants.join(', ') : 'Not specified', metaY + 16);
    doc.y = metaY + 40;

    // ── Executive Summary box ──
    sectionTitle(doc, '  EXECUTIVE SUMMARY', COLORS.brandDark);
    if (finalSummary) {
      const boxY = doc.y;
      const textH = doc.heightOfString(finalSummary, { width: doc.page.width - 124 });
      doc.rect(50, boxY, doc.page.width - 100, textH + 20).fill(COLORS.light);
      doc.rect(50, boxY, 4, textH + 20).fill(COLORS.brand);
      doc.font(FONT.oblique).fontSize(10.5).fillColor(COLORS.text);
      doc.text(finalSummary, 62, boxY + 10, { width: doc.page.width - 124 });
      doc.y = boxY + textH + 28;
    }

    // ── Key Discussion Points ──
    if (keyDiscussionPoints.length) {
      sectionTitle(doc, '  KEY DISCUSSION POINTS', COLORS.accent);
      keyDiscussionPoints.forEach((pt) => bulletItem(doc, pt));
    }

    // ── Decisions ──
    if (decisionsTaken.length) {
      sectionTitle(doc, '  DECISIONS TAKEN', COLORS.brand);
      decisionsTaken.forEach((d) => bulletItem(doc, d));
    }

    // ── Action Items table ──
    if (actionItems.length) {
      sectionTitle(doc, '  ACTION ITEMS', COLORS.danger);
      const colX = { task: 55, owner: 260, deadline: 390 };
      const headerY = doc.y;

      // Column headers
      doc.rect(50, headerY, doc.page.width - 100, 18).fill('#FEE2E2');
      doc.font(FONT.bold).fontSize(9).fillColor(COLORS.danger);
      doc.text('Task', colX.task, headerY + 5);
      doc.text('Owner', colX.owner, headerY + 5);
      doc.text('Deadline', colX.deadline, headerY + 5);
      doc.y = headerY + 22;

      actionItems.forEach((a, i) => {
        if (doc.y > doc.page.height - 60) doc.addPage();
        const rowY = doc.y;
        if (i % 2 === 0) doc.rect(50, rowY, doc.page.width - 100, 18).fill('#FFF5F5');
        doc.font(FONT.regular).fontSize(9.5).fillColor(COLORS.text);
        doc.text(a.task || '—', colX.task, rowY + 4, { width: 195 });
        doc.text(a.owner || 'Unassigned', colX.owner, rowY + 4, { width: 120 });
        doc.text(a.deadline || 'TBD', colX.deadline, rowY + 4, { width: 120 });
        doc.y = rowY + 22;
      });
      doc.moveDown(0.5);
    }

    // ── Next Meeting Agenda ──
    if (nextMeetingAgenda.length) {
      sectionTitle(doc, '  NEXT MEETING AGENDA', COLORS.purple);
      nextMeetingAgenda.forEach((a) => bulletItem(doc, a));
    }

    // Footer watermark
    doc.moveDown(1);
    doc.font(FONT.oblique).fontSize(8).fillColor(COLORS.muted);
    doc.text(`Generated by MeetCut on ${new Date().toLocaleString()}`, { align: 'center' });

    addPageNumbers(doc);
    doc.end();
  });
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatDuration(secs) {
  const h = Math.floor(secs / 3600);
  const m = Math.floor((secs % 3600) / 60);
  const s = Math.floor(secs % 60);
  const parts = [];
  if (h) parts.push(`${h}h`);
  if (m) parts.push(`${m}m`);
  if (s) parts.push(`${s}s`);
  return parts.join(' ') || '0s';
}
