import { useState, useEffect } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import LoadingSpinner from "../components/common/LoadingSpinner";
import {
  FaArrowLeft, FaDownload, FaFileAlt, FaUsers, FaClock,
  FaCheckCircle, FaListUl, FaQuestionCircle, FaChevronDown,
  FaChevronUp, FaExclamationCircle
} from "react-icons/fa";
import { MdSummarize } from "react-icons/md";
import jsPDF from "jspdf";
import { getUser, API } from "../utils/auth";
import toast from "react-hot-toast";

// ─── Tab config ───────────────────────────────────────────────────────────────
const TABS = [
  { id: "transcript",  label: "Transcript",    icon: <FaFileAlt /> },
  { id: "summary",     label: "AI Summary",     icon: <MdSummarize className="text-base" /> },
  { id: "actions",     label: "Action Items",   icon: <FaListUl /> },
  { id: "faqs",        label: "FAQs",           icon: <FaQuestionCircle /> },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────
function formatDuration(s) {
  if (!s) return "N/A";
  const m = Math.floor(s / 60);
  const sec = Math.round(s % 60);
  return `${m}m ${sec}s`;
}

function formatDate(str) {
  if (!str) return "N/A";
  const d = new Date(str);
  return isNaN(d) ? str : d.toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" });
}

// ─── PDF Generator ────────────────────────────────────────────────────────────
function downloadPDF(transcript) {
  const doc   = new jsPDF({ unit: "mm", format: "a4" });
  const PW    = 210;
  const PH    = 297;
  const ML    = 15;
  const MR    = 15;
  const TW    = PW - ML - MR;
  let y       = 20;

  const summary     = transcript.summary || {};
  const meetingTitle = summary.meetingTitle || transcript.meetingTitle || "Untitled Meeting";

  // ── Helper functions ────────────────────────────────────────────────────────
  function checkPage(needed = 10) {
    if (y + needed > PH - 15) {
      doc.addPage();
      y = 20;
    }
  }

  function addSection(title) {
    checkPage(16);
    y += 4;
    doc.setFillColor(239, 246, 255);
    doc.roundedRect(ML - 2, y - 5, TW + 4, 10, 2, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(29, 78, 216);
    doc.text(title, ML, y);
    y += 8;
    doc.setTextColor(31, 41, 55);
  }

  function addBodyText(text, indent = 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(55, 65, 81);
    const lines = doc.splitTextToSize(text, TW - indent);
    lines.forEach(line => {
      checkPage(6);
      doc.text(line, ML + indent, y);
      y += 5.5;
    });
  }

  function addBullet(text, color = [59, 130, 246]) {
    checkPage(8);
    doc.setFillColor(...color);
    doc.circle(ML + 2, y - 1.5, 1.2, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(55, 65, 81);
    const lines = doc.splitTextToSize(text, TW - 8);
    lines.forEach((line, i) => {
      checkPage(6);
      doc.text(line, ML + 6, y);
      y += 5.5;
    });
    y += 0.5;
  }

  // ── Cover ───────────────────────────────────────────────────────────────────
  doc.setFillColor(29, 78, 216);
  doc.rect(0, 0, PW, 45, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  const titleLines = doc.splitTextToSize(meetingTitle, TW);
  titleLines.forEach(line => { doc.text(line, ML, y); y += 9; });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(191, 219, 254);
  doc.text("Generated by MeetCut · " + new Date().toLocaleDateString("en-IN"), ML, y);
  y = 58;

  // ── Meta row ─────────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  const meta = [
    "Date: " + formatDate(transcript.meetingDate || transcript.createdAt),
    "Duration: " + formatDuration(transcript.durationSeconds),
    "Language: " + (transcript.language || "—").toUpperCase(),
  ].join("   |   ");
  doc.text(meta, ML, y);
  y += 10;
  doc.setDrawColor(226, 232, 240);
  doc.line(ML, y, PW - MR, y);
  y += 8;

  // ── Participants ──────────────────────────────────────────────────────────────
  const parts = summary.participants || transcript.participants || [];
  if (parts.length > 0) {
    addSection("👥 Participants");
    addBodyText(parts.join(", "));
    y += 3;
  }

  // ── Final Summary ─────────────────────────────────────────────────────────────
  if (summary.finalSummary) {
    addSection("📝 Executive Summary");
    addBodyText(summary.finalSummary);
    y += 3;
  }

  // ── Key Discussion Points ────────────────────────────────────────────────────
  if (summary.keyDiscussionPoints?.length > 0) {
    addSection("💬 Key Discussion Points");
    summary.keyDiscussionPoints.forEach(pt => addBullet(pt));
    y += 3;
  }

  // ── Decisions ────────────────────────────────────────────────────────────────
  if (summary.decisionsTaken?.length > 0) {
    addSection("✅ Decisions Taken");
    summary.decisionsTaken.forEach(d => addBullet(d, [34, 197, 94]));
    y += 3;
  }

  // ── Action Items ─────────────────────────────────────────────────────────────
  if (summary.actionItems?.length > 0) {
    addSection("🎯 Action Items");
    summary.actionItems.forEach(a => {
      checkPage(10);
      const task = `${a.task}`;
      const meta = [a.owner !== "Unassigned" && a.owner, a.deadline !== "TBD" && a.deadline]
        .filter(Boolean).join(" · ");
      addBullet(task + (meta ? `  [${meta}]` : ""), [249, 115, 22]);
    });
    y += 3;
  }

  // ── Next Meeting Agenda ───────────────────────────────────────────────────────
  if (summary.nextMeetingAgenda?.length > 0) {
    addSection("📅 Next Meeting Agenda");
    summary.nextMeetingAgenda.forEach(a => addBullet(a, [168, 85, 247]));
    y += 3;
  }

  // ── Full Transcript ───────────────────────────────────────────────────────────
  if (transcript.segments?.length > 0 || transcript.fullText) {
    doc.addPage();
    y = 20;
    addSection("📄 Full Transcript");
    y += 2;

    if (transcript.segments?.length > 0) {
      transcript.segments.forEach(seg => {
        checkPage(14);
        // Speaker + timestamp
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8.5);
        doc.setTextColor(29, 78, 216);
        const speaker = seg.speaker ? `${seg.speaker}` : "Speaker";
        const time    = seg.startFormatted ? ` [${seg.startFormatted}]` : "";
        doc.text(speaker + time, ML, y);
        y += 5;
        // Text
        addBodyText(seg.text, 0);
        y += 2;
      });
    } else if (transcript.fullText) {
      addBodyText(transcript.fullText);
    }
  }

  // ── Footer on each page ──────────────────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(`MeetCut · Page ${i} of ${totalPages}`, ML, PH - 8);
    doc.text(meetingTitle, PW / 2, PH - 8, { align: "center" });
  }

  doc.save(`MeetCut_Transcript_${Date.now()}.pdf`);
  toast.success("PDF downloaded!");
}

// ─── FAQ Generator (derives from summary) ────────────────────────────────────
function deriveFAQs(summary) {
  if (!summary) return [];
  const faqs = [];

  if (summary.finalSummary) {
    faqs.push({
      q: "What was this meeting about?",
      a: summary.finalSummary,
    });
  }
  if (summary.decisionsTaken?.length > 0) {
    faqs.push({
      q: "What decisions were made?",
      a: summary.decisionsTaken.join("\n"),
    });
  }
  if (summary.actionItems?.length > 0) {
    faqs.push({
      q: "What are the next steps / action items?",
      a: summary.actionItems.map(a => `• ${a.task}${a.owner && a.owner !== "Unassigned" ? ` (${a.owner})` : ""}${a.deadline && a.deadline !== "TBD" ? ` — due ${a.deadline}` : ""}`).join("\n"),
    });
  }
  if (summary.nextMeetingAgenda?.length > 0) {
    faqs.push({
      q: "What will be discussed in the next meeting?",
      a: summary.nextMeetingAgenda.join("\n"),
    });
  }
  if (summary.participants?.length > 0) {
    faqs.push({
      q: "Who attended this meeting?",
      a: summary.participants.join(", "),
    });
  }
  if (summary.keyDiscussionPoints?.length > 0) {
    faqs.push({
      q: "What were the main topics covered?",
      a: summary.keyDiscussionPoints.map(p => `• ${p}`).join("\n"),
    });
  }
  return faqs;
}

// ─── Component ────────────────────────────────────────────────────────────────
export default function TranscriptView() {
  const { id }     = useParams();
  const navigate   = useNavigate();
  const { token }  = getUser();

  const [transcript, setTranscript] = useState(null);
  const [loading, setLoading]       = useState(true);
  const [activeTab, setActiveTab]   = useState("transcript");
  const [openFAQ, setOpenFAQ]       = useState(null);

  useEffect(() => {
    async function fetchTranscript() {
      setLoading(true);
      try {
        const res  = await fetch(`${API}/api/audio/transcripts/${id}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data = await res.json();
        if (data.success) setTranscript(data.transcript);
        else toast.error(data.message || "Could not load transcript");
      } catch {
        toast.error("Server connection failed");
      } finally {
        setLoading(false);
      }
    }
    fetchTranscript();
  }, [id, token]);

  if (loading) {
    return <LoadingSpinner message="Loading transcript..." />;
  }

  if (!transcript) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-gray-50">
        <div className="text-center text-gray-500">
          <FaExclamationCircle className="text-4xl text-red-400 mx-auto mb-3" />
          <p className="font-semibold">Transcript not found</p>
          <button onClick={() => navigate("/meetings")} className="mt-4 text-blue-500 hover:underline text-sm">
            ← Back to Meetings
          </button>
        </div>
      </div>
    );
  }

  const summary = transcript.summary || {};
  const faqs    = deriveFAQs(summary);

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-5xl mx-auto px-6 py-8">

        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <Link
            to={`/meetings/${id}`}
            className="flex items-center gap-2 text-gray-500 hover:text-blue-600 text-sm transition"
          >
            <FaArrowLeft /> Back to Details
          </Link>
        </div>

        <div className="flex items-start justify-between mb-6 flex-wrap gap-4">
          <div>
            <h1 className="text-2xl font-bold text-gray-800">
              {summary.meetingTitle || transcript.meetingTitle || "Untitled Meeting"}
            </h1>
            <div className="flex items-center gap-4 mt-2 text-sm text-gray-500 flex-wrap">
              <span className="flex items-center gap-1.5">
                <FaClock className="text-blue-400 text-xs" />
                {formatDuration(transcript.durationSeconds)}
              </span>
              <span className="flex items-center gap-1.5">
                <FaUsers className="text-green-400 text-xs" />
                {(summary.participants || transcript.participants || []).length} participants
              </span>
              <span className="flex items-center gap-1.5">
                <FaCheckCircle className="text-purple-400 text-xs" />
                {formatDate(transcript.meetingDate || transcript.createdAt)}
              </span>
            </div>
          </div>

          <button
            onClick={() => downloadPDF(transcript)}
            className="flex items-center gap-2 px-5 py-2.5 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 transition font-semibold shadow-sm"
          >
            <FaDownload /> Download PDF
          </button>
        </div>

        {/* Tabs */}
        <div className="flex gap-1 bg-gray-200 p-1 rounded-xl mb-6 w-fit">
          {TABS.map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition ${
                activeTab === tab.id
                  ? "bg-white text-blue-600 shadow-sm"
                  : "text-gray-600 hover:text-gray-800"
              }`}
            >
              {tab.icon} {tab.label}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        <div className="bg-white rounded-xl border border-gray-100 shadow-sm">

          {/* ── Transcript Tab ───────────────────────────────────────────────── */}
          {activeTab === "transcript" && (
            <div className="p-6">
              <h2 className="font-semibold text-gray-800 mb-4 flex items-center gap-2">
                <FaFileAlt className="text-blue-500" /> Full Transcript
              </h2>

              {transcript.segments?.length > 0 ? (
                <div className="space-y-5 max-h-[65vh] overflow-y-auto pr-2 custom-scroll">
                  {transcript.segments.map((seg, i) => (
                    <div key={i} className="flex gap-4">
                      {/* Timeline dot */}
                      <div className="flex flex-col items-center shrink-0">
                        <div className="w-2.5 h-2.5 rounded-full bg-blue-400 mt-1.5" />
                        {i < transcript.segments.length - 1 && (
                          <div className="w-0.5 flex-1 bg-gray-100 mt-1" />
                        )}
                      </div>
                      <div className="pb-4 flex-1">
                        <div className="flex items-center gap-3 mb-1">
                          <span className="font-semibold text-sm text-gray-800">
                            {seg.speaker || "Speaker"}
                          </span>
                          {seg.startFormatted && (
                            <span className="text-xs text-gray-400 bg-gray-100 px-2 py-0.5 rounded-full">
                              {seg.startFormatted}
                            </span>
                          )}
                        </div>
                        <p className="text-sm text-gray-700 leading-relaxed">{seg.text}</p>
                      </div>
                    </div>
                  ))}
                </div>
              ) : transcript.fullText ? (
                <div className="max-h-[65vh] overflow-y-auto pr-2 custom-scroll">
                  <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                    {transcript.fullText}
                  </p>
                </div>
              ) : (
                <div className="text-center py-12 text-gray-400">
                  <FaFileAlt className="text-4xl mx-auto mb-3 text-gray-200" />
                  <p>No transcript available yet</p>
                </div>
              )}
            </div>
          )}

          {/* ── Summary Tab ───────────────────────────────────────────────────── */}
          {activeTab === "summary" && (
            <div className="p-6 space-y-6">
              <h2 className="font-semibold text-gray-800 flex items-center gap-2">
                <MdSummarize className="text-green-500 text-lg" /> AI Summary
              </h2>

              {!summary.finalSummary ? (
                <div className="text-center py-12 text-gray-400">
                  <MdSummarize className="text-4xl mx-auto mb-3 text-gray-200" />
                  <p>No summary generated yet</p>
                </div>
              ) : (
                <>
                  {/* Executive Summary */}
                  <div className="bg-blue-50 rounded-xl p-5 border border-blue-100">
                    <p className="text-sm font-semibold text-blue-600 mb-2 uppercase tracking-wider">Executive Summary</p>
                    <p className="text-gray-700 text-sm leading-relaxed">{summary.finalSummary}</p>
                  </div>

                  {/* Key Points + Decisions in 2-col */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                    {summary.keyDiscussionPoints?.length > 0 && (
                      <SummarySection
                        title="Key Discussion Points"
                        color="blue"
                        items={summary.keyDiscussionPoints}
                        bullet="•"
                      />
                    )}
                    {summary.decisionsTaken?.length > 0 && (
                      <SummarySection
                        title="Decisions Taken"
                        color="green"
                        items={summary.decisionsTaken}
                        bullet="✓"
                      />
                    )}
                  </div>

                  {summary.nextMeetingAgenda?.length > 0 && (
                    <SummarySection
                      title="Next Meeting Agenda"
                      color="purple"
                      items={summary.nextMeetingAgenda}
                      bullet="→"
                    />
                  )}

                  {summary.participants?.length > 0 && (
                    <div>
                      <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">
                        Participants
                      </p>
                      <div className="flex flex-wrap gap-2">
                        {summary.participants.map((p, i) => (
                          <span key={i} className="px-3 py-1 bg-gray-100 text-gray-700 text-sm rounded-full">
                            {p}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </>
              )}
            </div>
          )}

          {/* ── Action Items Tab ──────────────────────────────────────────────── */}
          {activeTab === "actions" && (
            <div className="p-6">
              <h2 className="font-semibold text-gray-800 mb-4 flex items-center gap-2">
                <FaListUl className="text-orange-500" /> Action Items
              </h2>

              {!summary.actionItems?.length ? (
                <div className="text-center py-12 text-gray-400">
                  <FaListUl className="text-4xl mx-auto mb-3 text-gray-200" />
                  <p>No action items found</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {summary.actionItems.map((item, i) => (
                    <div
                      key={i}
                      className="flex items-start gap-4 p-4 rounded-xl border border-orange-100 bg-orange-50 hover:border-orange-200 transition"
                    >
                      <div className="w-7 h-7 rounded-full bg-orange-400 text-white flex items-center justify-center text-xs font-bold shrink-0 mt-0.5">
                        {i + 1}
                      </div>
                      <div className="flex-1">
                        <p className="text-sm font-medium text-gray-800">{item.task}</p>
                        <div className="flex gap-4 mt-1.5 flex-wrap">
                          {item.owner && item.owner !== "Unassigned" && (
                            <span className="flex items-center gap-1 text-xs text-gray-500">
                              <FaUsers className="text-xs" /> {item.owner}
                            </span>
                          )}
                          {item.deadline && item.deadline !== "TBD" && (
                            <span className="flex items-center gap-1 text-xs text-gray-500">
                              <FaClock className="text-xs" /> {item.deadline}
                            </span>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* ── FAQs Tab ─────────────────────────────────────────────────────── */}
          {activeTab === "faqs" && (
            <div className="p-6">
              <h2 className="font-semibold text-gray-800 mb-4 flex items-center gap-2">
                <FaQuestionCircle className="text-purple-500" /> Frequently Asked Questions
              </h2>
              <p className="text-xs text-gray-400 mb-5">Auto-generated from the AI analysis of this meeting.</p>

              {faqs.length === 0 ? (
                <div className="text-center py-12 text-gray-400">
                  <FaQuestionCircle className="text-4xl mx-auto mb-3 text-gray-200" />
                  <p>No summary available to generate FAQs</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {faqs.map((faq, i) => (
                    <div
                      key={i}
                      className="border border-gray-100 rounded-xl overflow-hidden"
                    >
                      <button
                        onClick={() => setOpenFAQ(openFAQ === i ? null : i)}
                        className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-gray-50 transition"
                      >
                        <span className="font-medium text-gray-800 text-sm pr-4">{faq.q}</span>
                        <span className="text-gray-400 shrink-0">
                          {openFAQ === i ? <FaChevronUp /> : <FaChevronDown />}
                        </span>
                      </button>
                      {openFAQ === i && (
                        <div className="px-5 pb-4 border-t border-gray-100 bg-gray-50">
                          <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-line pt-3">
                            {faq.a}
                          </p>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function SummarySection({ title, color, items, bullet }) {
  const colors = {
    blue:   "text-blue-600 bg-blue-50 border-blue-100",
    green:  "text-green-600 bg-green-50 border-green-100",
    purple: "text-purple-600 bg-purple-50 border-purple-100",
    orange: "text-orange-600 bg-orange-50 border-orange-100",
  };
  const bulletColors = {
    blue: "text-blue-400", green: "text-green-500", purple: "text-purple-500", orange: "text-orange-400"
  };
  return (
    <div className={`rounded-xl p-4 border ${colors[color]}`}>
      <p className={`text-xs font-semibold uppercase tracking-wider mb-3 ${colors[color].split(" ")[0]}`}>
        {title}
      </p>
      <ul className="space-y-2">
        {items.map((item, i) => (
          <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
            <span className={`${bulletColors[color]} shrink-0 mt-0.5`}>{bullet}</span>
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}