import { useState, useRef } from "react";
import { Link, useNavigate } from "react-router-dom";
import {
  FaVideo, FaRobot, FaCog, FaListAlt, FaFileAlt,
  FaDownload, FaFilePdf, FaFileWord, FaUpload, FaSpinner,
  FaCheckCircle, FaTimesCircle, FaClipboard
} from "react-icons/fa";
import { MdDashboard, MdSummarize } from "react-icons/md";
import axios from "axios";
import { jsPDF } from "jspdf";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, UnderlineType } from "docx";

// ─── Sidebar ────────────────────────────────────────────────────────────────
function SidebarItem({ icon, label, path, active }) {
  return (
    <Link
      to={path}
      className={`flex items-center gap-3 px-4 py-2 rounded-lg cursor-pointer transition font-medium text-base ${
        active
          ? "bg-blue-100 text-blue-700 font-semibold"
          : "text-gray-700 hover:bg-blue-50"
      }`}
    >
      <span className="text-lg">{icon}</span>
      <span>{label}</span>
    </Link>
  );
}

// ─── PDF Export ─────────────────────────────────────────────────────────────
function exportToPDF(summary) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const usableW = pageW - margin * 2;
  let y = 20;

  function addPage() {
    doc.addPage();
    y = 20;
  }

  function checkY(needed = 10) {
    if (y + needed > 270) addPage();
  }

  // Header bar
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageW, 14, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("MeetCut — Meeting Summary", margin, 9);
  doc.text(new Date().toLocaleDateString(), pageW - margin, 9, { align: "right" });

  y = 22;

  // Title
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(summary.meetingTitle || "Meeting Summary", usableW);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 7 + 2;

  // DateTime & Participants
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(107, 114, 128);
  doc.text(`📅 ${summary.dateTime || "Not specified"}`, margin, y);
  y += 5;
  if (summary.participants?.length) {
    doc.text(`👥 ${summary.participants.join(", ")}`, margin, y);
    y += 5;
  }

  // Divider
  y += 3;
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  function sectionHeader(title, color = [37, 99, 235]) {
    checkY(12);
    doc.setFillColor(...color);
    doc.roundedRect(margin, y, usableW, 7, 1, 1, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin + 3, y + 5);
    y += 10;
    doc.setTextColor(17, 24, 39);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
  }

  function bulletList(items) {
    items.forEach((item) => {
      checkY(8);
      const text = typeof item === "string" ? item : `${item.task} — ${item.owner} (${item.deadline})`;
      const lines = doc.splitTextToSize(`• ${text}`, usableW - 4);
      lines.forEach((line, i) => {
        doc.text(i === 0 ? line : `  ${line}`, margin + 3, y);
        y += 5;
      });
    });
    y += 2;
  }

  // Final Summary box
  sectionHeader("📋 Executive Summary", [17, 24, 39]);
  const sumLines = doc.splitTextToSize(summary.finalSummary || "", usableW - 6);
  doc.setFillColor(249, 250, 251);
  doc.roundedRect(margin, y, usableW, sumLines.length * 5 + 6, 2, 2, "F");
  doc.setTextColor(55, 65, 81);
  sumLines.forEach((line) => { doc.text(line, margin + 3, y + 4); y += 5; });
  y += 6;

  if (summary.keyDiscussionPoints?.length) {
    sectionHeader("💬 Key Discussion Points", [5, 150, 105]);
    bulletList(summary.keyDiscussionPoints);
  }
  if (summary.decisionsTaken?.length) {
    sectionHeader("✅ Decisions Taken", [37, 99, 235]);
    bulletList(summary.decisionsTaken);
  }
  if (summary.actionItems?.length) {
    sectionHeader("⚡ Action Items", [220, 38, 38]);
    bulletList(summary.actionItems);
  }
  if (summary.nextMeetingAgenda?.length) {
    sectionHeader("📅 Next Meeting Agenda", [124, 58, 237]);
    bulletList(summary.nextMeetingAgenda);
  }

  // Footer
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(`Page ${i} of ${totalPages} — Generated by MeetCut`, pageW / 2, 290, { align: "center" });
  }

  doc.save(`MeetCut_Summary_${Date.now()}.pdf`);
}

// ─── DOCX Export ────────────────────────────────────────────────────────────
async function exportToDOCX(summary) {
  const heading = (text, level = HeadingLevel.HEADING_2) =>
    new Paragraph({
      text,
      heading: level,
      spacing: { before: 300, after: 100 },
    });

  const bullet = (text) =>
    new Paragraph({
      children: [new TextRun({ text: `• ${text}`, size: 22 })],
      spacing: { after: 80 },
      indent: { left: 400 },
    });

  const children = [
    new Paragraph({
      children: [
        new TextRun({
          text: summary.meetingTitle || "Meeting Summary",
          bold: true,
          size: 36,
          color: "2563EB",
        }),
      ],
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `Date/Time: `, bold: true, size: 22 }),
        new TextRun({ text: summary.dateTime || "Not specified", size: 22 }),
      ],
      spacing: { after: 80 },
    }),
  ];

  if (summary.participants?.length) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `Participants: `, bold: true, size: 22 }),
          new TextRun({ text: summary.participants.join(", "), size: 22 }),
        ],
        spacing: { after: 200 },
      })
    );
  }

  // Divider
  children.push(new Paragraph({ text: "─".repeat(60), spacing: { after: 200 } }));

  // Executive Summary
  children.push(heading("📋 Executive Summary"));
  children.push(
    new Paragraph({
      children: [new TextRun({ text: summary.finalSummary || "", size: 22, italics: true })],
      spacing: { after: 200 },
    })
  );

  if (summary.keyDiscussionPoints?.length) {
    children.push(heading("💬 Key Discussion Points"));
    summary.keyDiscussionPoints.forEach((p) => children.push(bullet(p)));
  }
  if (summary.decisionsTaken?.length) {
    children.push(heading("✅ Decisions Taken"));
    summary.decisionsTaken.forEach((d) => children.push(bullet(d)));
  }
  if (summary.actionItems?.length) {
    children.push(heading("⚡ Action Items"));
    summary.actionItems.forEach((a) =>
      children.push(bullet(`${a.task} — Owner: ${a.owner} | Deadline: ${a.deadline}`))
    );
  }
  if (summary.nextMeetingAgenda?.length) {
    children.push(heading("📅 Next Meeting Agenda"));
    summary.nextMeetingAgenda.forEach((a) => children.push(bullet(a)));
  }

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `\nGenerated by MeetCut on ${new Date().toLocaleString()}`,
          size: 18,
          color: "9CA3AF",
          italics: true,
        }),
      ],
      spacing: { before: 400 },
    })
  );

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `MeetCut_Summary_${Date.now()}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Main Page ───────────────────────────────────────────────────────────────
export default function SummaryGenerator() {
  const [transcript, setTranscript] = useState("");
  const [title, setTitle] = useState("");
  const [date, setDate] = useState("");
  const [participants, setParticipants] = useState("");
  const [inputMode, setInputMode] = useState("paste"); // paste | file
  const [fileName, setFileName] = useState("");
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState(null);
  const [error, setError] = useState("");
  const [exportingPdf, setExportingPdf] = useState(false);
  const [exportingDocx, setExportingDocx] = useState(false);
  const [copied, setCopied] = useState(false);
  const fileRef = useRef();

  const navigate = useNavigate();
  const token = localStorage.getItem("token");

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = (ev) => setTranscript(ev.target.result);
    reader.readAsText(file);
  };

  const handleGenerate = async () => {
    if (!transcript.trim()) {
      setError("Please paste or upload a meeting transcript.");
      return;
    }
    setError("");
    setLoading(true);
    setSummary(null);
    try {
      const res = await axios.post(
        "http://localhost:3000/api/summary/generate",
        { transcript, title, date, participants },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setSummary(res.data.summary);
    } catch (err) {
      setError(err.response?.data?.message || "Failed to generate summary. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!summary) return;
    const text = `
MEETING SUMMARY — ${summary.meetingTitle}
Date: ${summary.dateTime}
Participants: ${summary.participants?.join(", ")}

EXECUTIVE SUMMARY
${summary.finalSummary}

KEY DISCUSSION POINTS
${summary.keyDiscussionPoints?.map((p) => `• ${p}`).join("\n")}

DECISIONS TAKEN
${summary.decisionsTaken?.map((d) => `• ${d}`).join("\n")}

ACTION ITEMS
${summary.actionItems?.map((a) => `• ${a.task} — ${a.owner} (${a.deadline})`).join("\n")}
    `.trim();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex min-h-screen bg-gray-50">
      {/* Sidebar */}
      <aside className="w-64 bg-white border-r flex flex-col py-6 px-4 shrink-0">
        <h1 className="text-blue-600 font-bold text-xl mb-8">MeetCut</h1>
        <nav className="flex flex-col gap-2">
          <SidebarItem icon={<MdDashboard />} label="Dashboard" path="/dashboard" />
          <SidebarItem icon={<FaVideo />} label="Upload Video" path="/upload" />
          <SidebarItem icon={<FaRobot />} label="Create Bot" path="/create-bot" />
          <SidebarItem icon={<MdSummarize />} label="Summary Generator" path="/summary" active />
          <SidebarItem icon={<FaListAlt />} label="My Meetings" path="/meetings" />
          <SidebarItem icon={<FaCog />} label="Settings" path="/settings" />
        </nav>
      </aside>

      {/* Main */}
      <main className="flex-1 px-8 py-8 overflow-y-auto">
        <div className="max-w-5xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
              <MdSummarize className="text-blue-600" /> Meeting Summary Generator
            </h1>
            <p className="text-gray-500 mt-1">
              Paste or upload your meeting transcript → AI generates a professional summary → Export as PDF or DOCX
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* ── Input Panel ── */}
            <div className="space-y-4">
              {/* Optional metadata */}
              <div className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
                <h2 className="font-semibold text-gray-700 mb-3 flex items-center gap-2">
                  <FaFileAlt className="text-blue-500" /> Meeting Details (Optional)
                </h2>
                <div className="space-y-3">
                  <input
                    className="w-full border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300"
                    placeholder="Meeting Title (e.g. Q4 Strategy Review)"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                  />
                  <input
                    className="w-full border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300"
                    placeholder="Date (e.g. April 17, 2026)"
                    value={date}
                    onChange={(e) => setDate(e.target.value)}
                  />
                  <input
                    className="w-full border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300"
                    placeholder="Participants (e.g. Alice, Bob, Charlie)"
                    value={participants}
                    onChange={(e) => setParticipants(e.target.value)}
                  />
                </div>
              </div>

              {/* Transcript input */}
              <div className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
                <div className="flex gap-2 mb-3">
                  <button
                    onClick={() => setInputMode("paste")}
                    className={`px-4 py-1.5 rounded-full text-sm font-medium transition ${
                      inputMode === "paste"
                        ? "bg-blue-600 text-white"
                        : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                    }`}
                  >
                    Paste Text
                  </button>
                  <button
                    onClick={() => setInputMode("file")}
                    className={`px-4 py-1.5 rounded-full text-sm font-medium transition ${
                      inputMode === "file"
                        ? "bg-blue-600 text-white"
                        : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                    }`}
                  >
                    Upload File
                  </button>
                </div>

                {inputMode === "paste" ? (
                  <textarea
                    className="w-full border rounded-lg px-3 py-2 text-sm h-52 resize-none focus:outline-none focus:ring-2 focus:ring-blue-300"
                    placeholder="Paste your meeting transcript here...&#10;&#10;e.g.&#10;Alice: Let's start the Q4 review. We need to finalize the budget.&#10;Bob: I think we should allocate 40% to marketing.&#10;Charlie: Agreed. I'll handle the report by Friday."
                    value={transcript}
                    onChange={(e) => setTranscript(e.target.value)}
                  />
                ) : (
                  <div
                    onClick={() => fileRef.current.click()}
                    className="h-52 border-2 border-dashed border-blue-200 rounded-lg flex flex-col items-center justify-center cursor-pointer hover:border-blue-400 hover:bg-blue-50 transition"
                  >
                    <FaUpload className="text-blue-400 text-2xl mb-2" />
                    <p className="text-sm text-gray-500">
                      {fileName || "Click to upload a .txt file"}
                    </p>
                    <p className="text-xs text-gray-400 mt-1">Supports .txt, .md files</p>
                    <input
                      ref={fileRef}
                      type="file"
                      accept=".txt,.md,.text"
                      className="hidden"
                      onChange={handleFileChange}
                    />
                  </div>
                )}

                {transcript && (
                  <p className="text-xs text-gray-400 mt-2 text-right">
                    {transcript.length.toLocaleString()} characters
                  </p>
                )}
              </div>

              {/* Error */}
              {error && (
                <div className="flex items-center gap-2 bg-red-50 border border-red-200 rounded-lg px-4 py-3 text-red-600 text-sm">
                  <FaTimesCircle /> {error}
                </div>
              )}

              {/* Generate Button */}
              <button
                onClick={handleGenerate}
                disabled={loading}
                className="w-full bg-blue-600 hover:bg-blue-700 disabled:opacity-60 text-white font-semibold py-3 rounded-xl flex items-center justify-center gap-2 transition text-sm shadow-md"
              >
                {loading ? (
                  <>
                    <FaSpinner className="animate-spin" /> Generating Summary...
                  </>
                ) : (
                  <>
                    <MdSummarize /> Generate AI Summary
                  </>
                )}
              </button>

              {loading && (
                <p className="text-center text-xs text-gray-400 animate-pulse">
                  Groq AI is analyzing your transcript…
                </p>
              )}
            </div>

            {/* ── Summary Output Panel ── */}
            <div>
              {!summary && !loading && (
                <div className="bg-white rounded-xl border border-dashed border-gray-200 h-full flex flex-col items-center justify-center text-center p-10">
                  <MdSummarize className="text-gray-200 text-6xl mb-4" />
                  <p className="text-gray-400 font-medium">Your summary will appear here</p>
                  <p className="text-gray-300 text-sm mt-1">
                    Enter a transcript and click Generate
                  </p>
                </div>
              )}

              {loading && (
                <div className="bg-white rounded-xl border border-gray-200 h-full flex items-center justify-center p-10">
                  <div className="text-center">
                    <FaSpinner className="animate-spin text-blue-500 text-3xl mx-auto mb-3" />
                    <p className="text-gray-500 text-sm">Analyzing transcript with Groq AI…</p>
                  </div>
                </div>
              )}

              {summary && (
                <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
                  {/* Summary header */}
                  <div className="bg-gradient-to-r from-blue-600 to-blue-700 px-5 py-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <h2 className="text-white font-bold text-lg leading-tight">
                          {summary.meetingTitle}
                        </h2>
                        <p className="text-blue-200 text-sm mt-0.5">{summary.dateTime}</p>
                      </div>
                      <FaCheckCircle className="text-green-300 text-2xl shrink-0" />
                    </div>
                    {summary.participants?.length > 0 && (
                      <div className="flex flex-wrap gap-1 mt-2">
                        {summary.participants.map((p, i) => (
                          <span
                            key={i}
                            className="bg-blue-500 text-white text-xs px-2 py-0.5 rounded-full"
                          >
                            {p}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Export buttons */}
                  <div className="flex gap-2 px-5 py-3 bg-gray-50 border-b">
                    <button
                      onClick={() => { setExportingPdf(true); exportToPDF(summary); setTimeout(() => setExportingPdf(false), 1000); }}
                      disabled={exportingPdf}
                      className="flex items-center gap-1.5 bg-red-500 hover:bg-red-600 text-white text-xs font-semibold px-3 py-1.5 rounded-lg transition"
                    >
                      {exportingPdf ? <FaSpinner className="animate-spin" /> : <FaFilePdf />}
                      Export PDF
                    </button>
                    <button
                      onClick={async () => { setExportingDocx(true); await exportToDOCX(summary); setExportingDocx(false); }}
                      disabled={exportingDocx}
                      className="flex items-center gap-1.5 bg-blue-500 hover:bg-blue-600 text-white text-xs font-semibold px-3 py-1.5 rounded-lg transition"
                    >
                      {exportingDocx ? <FaSpinner className="animate-spin" /> : <FaFileWord />}
                      Export DOCX
                    </button>
                    <button
                      onClick={handleCopy}
                      className="flex items-center gap-1.5 bg-gray-200 hover:bg-gray-300 text-gray-700 text-xs font-semibold px-3 py-1.5 rounded-lg transition ml-auto"
                    >
                      {copied ? <FaCheckCircle className="text-green-500" /> : <FaClipboard />}
                      {copied ? "Copied!" : "Copy"}
                    </button>
                  </div>

                  {/* Summary sections */}
                  <div className="px-5 py-4 space-y-4 max-h-[60vh] overflow-y-auto">
                    <SummarySection title="📋 Executive Summary" color="blue">
                      <p className="text-gray-700 text-sm leading-relaxed italic">{summary.finalSummary}</p>
                    </SummarySection>

                    {summary.keyDiscussionPoints?.length > 0 && (
                      <SummarySection title="💬 Key Discussion Points" color="green">
                        <ul className="space-y-1">
                          {summary.keyDiscussionPoints.map((p, i) => (
                            <li key={i} className="text-sm text-gray-700 flex gap-2">
                              <span className="text-green-500 mt-0.5">•</span> {p}
                            </li>
                          ))}
                        </ul>
                      </SummarySection>
                    )}

                    {summary.decisionsTaken?.length > 0 && (
                      <SummarySection title="✅ Decisions Taken" color="blue">
                        <ul className="space-y-1">
                          {summary.decisionsTaken.map((d, i) => (
                            <li key={i} className="text-sm text-gray-700 flex gap-2">
                              <span className="text-blue-500 mt-0.5">✓</span> {d}
                            </li>
                          ))}
                        </ul>
                      </SummarySection>
                    )}

                    {summary.actionItems?.length > 0 && (
                      <SummarySection title="⚡ Action Items" color="red">
                        <div className="space-y-2">
                          {summary.actionItems.map((a, i) => (
                            <div key={i} className="bg-red-50 rounded-lg px-3 py-2 text-sm">
                              <p className="font-medium text-gray-800">{a.task}</p>
                              <p className="text-xs text-gray-500 mt-0.5">
                                👤 {a.owner} &nbsp;|&nbsp; 📅 {a.deadline}
                              </p>
                            </div>
                          ))}
                        </div>
                      </SummarySection>
                    )}

                    {summary.nextMeetingAgenda?.length > 0 && (
                      <SummarySection title="📅 Next Meeting Agenda" color="purple">
                        <ul className="space-y-1">
                          {summary.nextMeetingAgenda.map((a, i) => (
                            <li key={i} className="text-sm text-gray-700 flex gap-2">
                              <span className="text-purple-500 mt-0.5">→</span> {a}
                            </li>
                          ))}
                        </ul>
                      </SummarySection>
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

function SummarySection({ title, color, children }) {
  const colors = {
    blue: "text-blue-700 border-blue-200 bg-blue-50",
    green: "text-green-700 border-green-200 bg-green-50",
    red: "text-red-700 border-red-200 bg-red-50",
    purple: "text-purple-700 border-purple-200 bg-purple-50",
  };
  return (
    <div className={`rounded-lg border p-3 ${colors[color]}`}>
      <h3 className="font-semibold text-sm mb-2">{title}</h3>
      {children}
    </div>
  );
}
